apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: evermos-be
  description: testing service for testing
  tags:
    - php
  links:
    - url: https://evermos.com
      title: evermos
      icon: evermos
spec:
  type: service
  lifecycle: production
  owner: brandops
  dependsOn: ['component:testing', 'resource:evermos-db']
  system: sistem-portal-evermos
